### PR TITLE
Fixed headings in README

### PR DESCRIPTION
**Pull request by krizalys**
I believe this PR restores the original intent of the author.

### CODE REVIEW

**Comment by krizalys** [comment]
@stevepeak Any update on this?

**Comment by krizalys** [comment]
@stevepeak Any update on this?

**Comment by krizalys** [comment]
@stevepeak Any update on this?

**Review by bueltge — APPROVED** [review]

**Comment by krizalys** [comment]
@stevepeak Any update on this?

**Comment by krizalys** [comment]
@stevepeak Any update on this?

**Pull request merged**
